plugins {
    id 'java'
    id 'groovy'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'net.ltgt.errorprone' version '5.1.0'
    id 'net.ltgt.nullaway' version '3.0.0'
}

group = 'com.shootersplatform'
version = '0.0.1-SNAPSHOT'

ext['tomcat.version'] = '11.0.22'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencyLocking {
    lockAllConfigurations()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-jackson'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-flyway'
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.flywaydb:flyway-database-postgresql'
    implementation 'org.bouncycastle:bcprov-jdk18on:1.84'

    runtimeOnly 'org.postgresql:postgresql:42.7.11'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation platform('org.spockframework:spock-bom:2.4-groovy-5.0')
    testImplementation 'org.spockframework:spock-core'
    testImplementation 'org.spockframework:spock-spring'
    testImplementation "org.testcontainers:testcontainers-postgresql:2.0.1"

    errorprone 'com.google.errorprone:error_prone_core:2.49.0'
    errorprone 'com.uber.nullaway:nullaway:0.13.4'
}

tasks.named('test') {
    useJUnitPlatform()
}

nullaway {
    onlyNullMarked = true
    jspecifyMode = true
}

tasks.withType(JavaCompile).configureEach {
    options.errorprone.disableWarningsInGeneratedCode = true
    options.errorprone.nullaway {
        error()
        checkOptionalEmptiness = true
        acknowledgeRestrictiveAnnotations = true
        externalInitAnnotations.add('jakarta.persistence.Entity')
    }
}
