create table app_metadata (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    value varchar(255) not null,
    created_at timestamp with time zone not null default now()
);

insert into app_metadata (name, value)
values ('schema', 'initialized');
